name: CD/CI

on:
  push:
    branches:
      - stage
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user information
        run: |
          git config user.name "Ternala"
          git config user.email "share.ternala@gmail.com"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - uses: actions/checkout@v3
      - name: Commit changes
        run: |
          git add . 
          git commit -am "Build"
          git push

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user information
        run: |
          git config user.name "Ternala"
          git config user.email "share.ternala@gmail.com"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Publish
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
            npm version prerelease --preid=next
          else
            npm version patch
          fi
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}

      - uses: actions/checkout@v3
      - name: Commit changes
        run: |
          git add . 
          git commit -am "Publish new version"
          git push
